title: The Marblville lab Public Entries
author: aaronliu0130
email: aaronliu0130@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my new page! I really hope you like it. Subscribe to
  https://www.youtube.com/channel/UCvfqduLrAaBeQjexEEqVZfA?sub_confirmation=1

# social links
twitter_username: your-twitter-handle
github_username:  aaronliu0130

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
